version: "3.9"

networks:
  brilhador:
    driver: bridge
services:
  spring-boot:
    container_name: spring-boot
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - brilhador